### ISSUE TITLE
bs4Dash shiny app are loading very slowly when connect the internet

### ISSUE THREAD

**Issue by jeffywang3** [RinteRface/bs4Dash#140]
Is there anyone who met the issue that bs4Dash shiny app are loading very slowly. And I doubted that the app might be searching the net when loading. So I disconnect the net, and it's loading fastly as usual. 
So how to solve this problem, may be by suppressing connecting the net somehow in the bs4Dash shiny app.
Thanks in advance!

**Comment by DivadNojnarg** [comment]
Do you have a reproducible example?

**Comment by tpbp** [comment]
I experienced something similar to what jeffrywang3 is describing. It seems that an app using bs4Dash attempts to connect to fonts.googlepis.com and use.fontawesome.com and other websites when opened on a browser if you have an internet connection. If your connection is blocked (because of a proxy server, say) then the browser attempts to connect to these sites until it times out, which delays the loading of the app. There is no delay in loading the app when you are disconnected from the internet.

Is there a way of preventing bs4Dash from attempting to connect to those websites (I know it is the browser that is attempting the connection, but those attempts seem to come from bs4Dash requests)? Can a bs4Dash user disable these attempts somehow? Can we point bs4Dash to a local repository?

To reproduce this behavior you need an internet connection which is blocked somehow (eg. by a proxy server in which you haven't yet authenticated). You can use the bs4Dash template app which I copy below. I'm using bs4Dash 0.5.0.

library(shiny)
library(bs4Dash)


shiny::shinyApp(
  ui = bs4DashPage(
    navbar = bs4DashNavbar(),
    sidebar = bs4DashSidebar(
      skin = "light",
      bs4SidebarMenu(
        bs4SidebarHeader("Main content"),
        bs4SidebarMenuItem(
          "Classic theme",
          tabName = "classic",
          icon = "desktop"
        )
      )
    ),
    controlbar = bs4DashControlbar(
      skin = "light"
    ),
    footer = bs4DashFooter(),
    title = "Classic theme",
    body = bs4DashBody(
      bs4TabItems(
        bs4TabItem(
          tabName = "classic",
          fluidRow(
            bs4Box(
              height = "600px",
              title = "Box 1"
            ),
            bs4Box(
              height = "600px",
              title = "Box 2"
            )
          )
        )
      )
    )
  ),
  server = function(input, output) {}
)
