### ISSUE TITLE
Screen jumps up and down

### ISSUE THREAD

**Issue by tobiasblasberg** [RinteRface/bs4Dash#170]
Hi Dev-Team, 

The screen jumps up and down within the app and I could not yet figure out which elements are causing this behavior. Before migrating from the CRAN version of shinydashboard/shinydashboardPlus this was not happening. 

Is there any option to avoid this? Do you habve any idea what could be the trigger of this behavior?

Thank you and best,
Tobias

**Comment by karakastarik** [comment]
Hi,
I have the same problem, thanks.

Tarik

**Comment by DivadNojnarg** [comment]
Hi,

Would you have an example that shows the problem? Could you show me your `sessioninfo::session_info()`?
Thanks.

**Comment by karakastarik** [comment]
Hi, my session_info like that:

`sessioninfo::session_info()`

```
Session info --------------------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 4.0.3 (2020-10-10)
 os       Windows 10 x64              
 system   x86_64, mingw32             
 ui       RStudio                     
 language (EN)                                   
 date     2021-02-11
``` 
And issue is here:

https://user-images.githubusercontent.com/42123801/107680653-3178a980-6caf-11eb-9b8e-3e79c55a1943.mp4

I'm using v0.5.0 of Bs4Dash. Thanks for comment.

Tarik

**Comment by DivadNojnarg** [comment]
Do you have any custom JavaScript code in your app? It would help me to get access to the app, if it is possible. 

It could be a web browser related issue as `{bs4Dash}` 0.5.0 hasn't changed anymore since more than 1 year. The same old version is hosted here: https://rinterface.com/shiny/bs4Dash/classic/ and seems to run smoothly on all web browsers I have.

**Comment by tobiasblasberg** [comment]
I am using the current Github version and it seems to be an issue with Chrome but not on Safari. Unfortunately, I don't have a small example that I can share right now. 

@karakastarik , do you have a small example you can share?

**Comment by karakastarik** [comment]
No, I don't have any JavaScript code in my app. I tried it on three different PCs and two different browsers (Edge, Chrome) but still same. 

https://rinterface.com/shiny/bs4Dash/classic/  this version is working fine for me, no up/down jumps i don't think this issue is about web browser related.

In my opinion,
```
dashboardBody(
fluidrow(
     bs4card(),
     bs4card()
   )
)
```
is triggering this issue. I mean, when bs4Cards are placed side by side. It works fine when bs4cards are placed one under the other:
```
dashboardBody(
     bs4card(),
     bs4card()
)
```
My app is pretty big and contains confidential information/data so unfortunately I cannot share it, sorry for that.

**Comment by tobiasblasberg** [comment]
In my case it was actually caused by the package shinycssloaders. The bug is already discussed here: https://github.com/daattali/shinycssloaders/issues/54. Strange that this just causes issues with the bs4dash version and not the shinydashboard-CRAN-version. 
Maybe this can also fix your issues @karakastarik

**Comment by karakastarik** [comment]
@tobiasblasberg thanks a lot !  Now I understand what caused the issue. I will try mentioned solution.

**Comment by tobiasblasberg** [comment]
Adding the following css styling solved the issue for me: 

`  .loader { min-height: 40px; }`

**Comment by DivadNojnarg** [comment]
Good to know thanks!
