### ISSUE TITLE
No right border on collapsed sidebar menu items

### ISSUE THREAD

**Issue by aldomann** [RinteRface/bs4Dash#24]
For some reason, the collapsed sidebar items render as expected on RStudio:
![image](https://user-images.githubusercontent.com/729732/54117179-8ab76e80-43f0-11e9-80ba-d126e03ba818.png)

While on Chrome (72.0.3626.121) and Firefox (65.0.2) the right side of the sidebar items is extended till the right border of the sidebar:
![image](https://user-images.githubusercontent.com/729732/54116904-049b2800-43f0-11e9-94bb-4ba075ee74e6.png)

Any way to fix this? I've been inspecting the CSS code and haven't found any fix so far.

**Comment by DivadNojnarg** [comment]
This is quite embarrassing and bs4Dash has not changed since a while. I checked the adminLTE3 status and running the template shows the same issue. I guess this is related to chrome and firefox update. 

The adminLTE bug report is here https://github.com/almasaeed2010/AdminLTE/issues?page=2&q=is%3Aissue+is%3Aopen and I have not seen such issue yet. Please report your problem since at some point all users will be concerned. In the meantime, I will try to get a workaround. Thanks ;)

**Comment by aldomann** [comment]
Awesome, I thought it might have been an issue with Chrome's and Firefoxe's renderer.  Looking at the inspector it seems they are rendering the full sized button/item and the overflow is just being hidden as the sidebar is collapsed, like so:
![image](https://user-images.githubusercontent.com/729732/54121805-ae33e680-43fb-11e9-93ea-879ec627c6de.png)

**Comment by DivadNojnarg** [comment]
This is not the case in safari and Opera
![Capture d’écran 2019-03-11 à 13 39 45](https://user-images.githubusercontent.com/18291543/54124627-38cc1400-4403-11e9-9c27-58d97fb289d6.png)

But Brave returns the same issue.
