### ISSUE TITLE
Repo management

### ISSUE THREAD

**Issue by yogat3ch** [RinteRface/bs4Dash#278]
Hi @DivadNojnarg,
I greatly appreciate all the work you've done on this repo. We're actively developing with it, which brings me to the crux of this issue. 
There's passing PR requests that most users will likely find useful that have been open since 2019 that are still unmerged and the repo is languishing in the absence of active maintenance. 
Are you amenable to appointing more active maintainers for this repo and providing necessary permissions such that they can pick up the slack in maintaining this repo?

**Comment by DivadNojnarg** [comment]
Hi,

Thanks for sharing your concerns.

My current time blockers and higher priorities are:

- The RinteRface book -> https://github.com/DivadNojnarg/outstanding-shiny-ui, which you can order [here](https://www.routledge.com/Outstanding-User-Interfaces-with-Shiny/Granjon/p/book/9780367645267). This project will end in June when the book is printed, hopefully. This has taken almost all my open source time since 2 years and I am really looking forward to doing something else. 
- This ongoing [project](https://github.com/Novartis/shinyValidator) about Shiny apps testing will take my working time until end of June. This project is supported by Novartis so I am allowed to work on it. This is not the case with other RinteRface projects. 

Regarding any possible temporary maintainer, most RinteRface members like are fully booked for various reasons and can't ask them to maintain it even temporarily. 

On my side, things will get smoother starting from July.

Best, 

David

**Comment by yogat3ch** [comment]
Outstanding Shiny UI looks like a solid read! That's exciting you're nearly done with the book!
