### ISSUE TITLE
Minimize button will not display when box contained in other box

### ISSUE THREAD

**Issue by duanyu5871** [RinteRface/bs4Dash#346]
Hello, 
I find minimize button will not display when box is maximized both for the box you clicked and box contained in it. Is any method to avoid influence for other box?

Really need your help, Thanks

![image](https://github.com/RinteRface/bs4Dash/assets/15108185/cd8d0439-ab58-408e-b16e-23ae05383df5)

![image](https://github.com/RinteRface/bs4Dash/assets/15108185/7f359978-d3a1-4ee6-a9e0-cd96ae325e42)

**Comment by DivadNojnarg** [comment]
Hi,

This behavior comes from the card binding JavaScript, when the card has an `id`:

```js
if (isMaximized) {
      $(el)
        .find("[data-card-widget = 'collapse']")
        .hide();
}
```

This means that when the card is maximized, the collapse button is hidden, which makes sense because no one would like to collapse a card in this situation. 

In your case, since you have nested cards, this also applies for the nested card: under the hood, the `find` method returns all elements having the following attribute `[data-card-widget = 'collapse']` within the parent card. So if you had 5 nested cards, you would get 6 elements (5 + the parent collapse icon).  

I could technically fix it by only selecting the first element corresponding to the parent card:

```js
$(el).find("[data-card-widget = 'collapse']")[0] ...
```

Beyond this, I would not recommend nesting cards as it creates confusing user experience and unexpected effects like the one above. Instead you can use `tabBox()` or accordions/collapsible elements.

Any thoughts @JohnCoene ?

**Comment by DivadNojnarg** [comment]
Closing as this does not align with design best practices (nested cards). I don't want to encourage this approach.

**Comment by duanyu5871** [comment]
OK, Thank you anyway. I will try to handle it by myself.
