### ISSUE TITLE
Suggestion to clean up URL

### ISSUE THREAD

**Issue by ResourceX** [RinteRface/bs4Dash#73]
When I host an app the URL grows as the user clicks around. Would it be possible to turn off all the /_w_ strings that get added to the URL. Very cosmetic, I know and I'm likely naive, but I don't know what this is doing. Thank you.

For example, what is all this after /bs4DashDemo/

https://dgranjon.shinyapps.io/bs4DashDemo/_w_2e516194/_w_9ab1ab52/_w_f7431d38/

**Comment by DivadNojnarg** [comment]
This is just to ensure that bs4Dash works on all professional RStudio products (If you remove it, you will notice that tab navigation will fail). For instance, shiny apps.io allow to create new R processes based on the current load and each time a new worker is created there is an idea associated. What you see in the url is the workId, there is no bad intention behind it ;)

**Comment by ResourceX** [comment]
Thanks. I ran across this package and I like the functions for change_page, is_page as shown towards the end of this article. I like bs4Dash for all it's cool UI features. I wanted to be able to change tabs grammatically and tried to combine packages.

**Comment by ResourceX** [comment]
I did get this to work. I found workerID in bs4Dash.js in the inst folder and I just commented out window.history.replaceState. 

It's still a work in progress for me, I'm not sure if this will be beneficial in the end. But I was able to host an app on shinyserver and use the shiny.router package to control the tabs and the bs4Dash package for pretty UI elements. 

When hosting on shiny server I also had to update the href ="" to include the full URL name of my app.

```
var workerId = $('base').attr('href');
  // ensure that this code does not locally
  if (typeof workerId != "undefined") {
    var pathname = window.location.pathname;
    var newpath = pathname + workerId;
    //window.history.replaceState( {} , 'newpath', newpath);
  }
```

**Comment by DivadNojnarg** [comment]
This looks interesting. I don't have a lot of experience with shiny.router.

**Comment by ResourceX** [comment]
Neither do I. I thought it might be a way to help break up my app... Thanks for your help here. This package is great for a new look for shiny dashboards.

**Comment by aljrico** [comment]
Hi!

I am trying to deploy a Shiny App that, among other things, is capable of reading GET requests. This is possible if the user adds parameters to the address, like `https://myapp.shinyapps.io/?param1=4234&param2=2342`

Everything works perfectly until I moved the `shinydashboard` bits to `bs4Dash`. Whenever the user tries to input those parameters, the address gets quickly updated to https://myapp.shinyapps.io/w_88a98847/. So the request can't be captured.

Commenting out that line, as you mention, would be captured by shinyapps.io so that gets solved? Would that create other potential issues?
